# fly.toml file generated for wispy-dew-3749 on 2023-03-29T00:37:10-05:00

app = "wispy-dew-3749"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
